version: '3'

services:
  backend:
    build: ./backend
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/.env:/app/.env
    depends_on:
      - postgres_db
    networks:
      - app-network

  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '54320:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_db:
    driver: local